<?php
declare(strict_types=1);

// BudMcpModelContextProtocol SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BudMcpModelContextProtocolUtility::setRegistrar(function (BudMcpModelContextProtocolUtility $u): void {
    $u->clean = [BudMcpModelContextProtocolClean::class, 'call'];
    $u->done = [BudMcpModelContextProtocolDone::class, 'call'];
    $u->make_error = [BudMcpModelContextProtocolMakeError::class, 'call'];
    $u->feature_add = [BudMcpModelContextProtocolFeatureAdd::class, 'call'];
    $u->feature_hook = [BudMcpModelContextProtocolFeatureHook::class, 'call'];
    $u->feature_init = [BudMcpModelContextProtocolFeatureInit::class, 'call'];
    $u->fetcher = [BudMcpModelContextProtocolFetcher::class, 'call'];
    $u->make_fetch_def = [BudMcpModelContextProtocolMakeFetchDef::class, 'call'];
    $u->make_context = [BudMcpModelContextProtocolMakeContext::class, 'call'];
    $u->make_options = [BudMcpModelContextProtocolMakeOptions::class, 'call'];
    $u->make_request = [BudMcpModelContextProtocolMakeRequest::class, 'call'];
    $u->make_response = [BudMcpModelContextProtocolMakeResponse::class, 'call'];
    $u->make_result = [BudMcpModelContextProtocolMakeResult::class, 'call'];
    $u->make_point = [BudMcpModelContextProtocolMakePoint::class, 'call'];
    $u->make_spec = [BudMcpModelContextProtocolMakeSpec::class, 'call'];
    $u->make_url = [BudMcpModelContextProtocolMakeUrl::class, 'call'];
    $u->param = [BudMcpModelContextProtocolParam::class, 'call'];
    $u->prepare_auth = [BudMcpModelContextProtocolPrepareAuth::class, 'call'];
    $u->prepare_body = [BudMcpModelContextProtocolPrepareBody::class, 'call'];
    $u->prepare_headers = [BudMcpModelContextProtocolPrepareHeaders::class, 'call'];
    $u->prepare_method = [BudMcpModelContextProtocolPrepareMethod::class, 'call'];
    $u->prepare_params = [BudMcpModelContextProtocolPrepareParams::class, 'call'];
    $u->prepare_path = [BudMcpModelContextProtocolPreparePath::class, 'call'];
    $u->prepare_query = [BudMcpModelContextProtocolPrepareQuery::class, 'call'];
    $u->graphql_body = [BudMcpModelContextProtocolGraphql::class, 'body'];
    $u->graphql_errors = [BudMcpModelContextProtocolGraphql::class, 'errors'];
    $u->result_basic = [BudMcpModelContextProtocolResultBasic::class, 'call'];
    $u->result_body = [BudMcpModelContextProtocolResultBody::class, 'call'];
    $u->result_headers = [BudMcpModelContextProtocolResultHeaders::class, 'call'];
    $u->transform_request = [BudMcpModelContextProtocolTransformRequest::class, 'call'];
    $u->transform_response = [BudMcpModelContextProtocolTransformResponse::class, 'call'];
});
